name: alarm_app
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  uuid: ^3.0.7
  flutter_timezone: ^1.0.4
  awesome_notifications: ^0.7.4
  workmanager: ^0.5.1
  rate_limiter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

