name: alarm_app
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  uuid: ^3.0.7
  flutter_timezone: ^1.0.4
  awesome_notifications: ^0.7.4
  rate_limiter: ^1.0.0
  background_fetch: ^1.1.5
  simple_circular_progress_bar: ^1.0.2
  just_audio: ^0.9.32
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

